const SET_TOKEN = "SET_TOKEN";
const DELETE_TOKEN = "DELETE_TOKEN";
const GET_SEARCHS = "GET_SEARCHS"
const UPDATE_SEARCHS = "UPDATE_SEARCHS"

export {
  SET_TOKEN,
  DELETE_TOKEN,
  GET_SEARCHS,
  UPDATE_SEARCHS
}